name: 'meupatrocinio/docker-status-check-action'
description: 'Checks container health statuses.'

author: 'Patrick Almeida <patricktalmeida@gmail.com>'

inputs:
  container_name:
    description: 'Container name'
    required: true
  timeout:
    description: 'Checks timout'
    required: false
    default: 300

outputs:
  changes_detected:
    description: Value is "true", if the repository was dirty and file changes have been detected. Value is "false", if no changes have been detected.

branding:
  icon: 'git-commit'
  color: orange

runs:
  using: 'node12'
  main: 'index.js'
