name: Git Auto Commit
description: 'Checks container health statuses.'

author: Patrick Almeida <patricktalmeida@gmail.com>

inputs:
  container_name:
    description: Container name
    required: true
  timeout:
    description: Checks timout
    required: false
    default: 300

runs:
  using: 'node12'
  main: 'index.js'
