name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install testing dependencies
      run: yarn install

    - name: Run Tests
      run: yarn test

